artifact_uri: file:///D:/Data%20science/Portfolio%20Projects/churn_prediction/churn-prediction/mlruns/881745867395782832/61eacc213f9848ccb0af505fc90b3176/artifacts
end_time: 1780410850179
entry_point_name: ''
experiment_id: '881745867395782832'
lifecycle_stage: active
run_id: 61eacc213f9848ccb0af505fc90b3176
run_name: dapper-swan-121
source_name: ''
source_type: 4
source_version: ''
start_time: 1780410816199
status: 3
tags: []
user_id: Asus
