artifact_uri: file:///D:/Data%20science/Portfolio%20Projects/churn_prediction/churn-prediction/mlruns/881745867395782832/47c0e9ea9c024f1d8c5d26aafa68ad61/artifacts
end_time: 1780419010709
entry_point_name: ''
experiment_id: '881745867395782832'
lifecycle_stage: active
run_id: 47c0e9ea9c024f1d8c5d26aafa68ad61
run_name: judicious-skink-49
source_name: ''
source_type: 4
source_version: ''
start_time: 1780419010596
status: 4
tags: []
user_id: Asus
